package workflow

import (
	"fmt"
	"strings"

	"github.com/jbrunton/gflows/yaml"
)

// Definition - definitoin for a workflow defined by a GFlows template
type Definition struct {
	Name        string
	Source      string
	Destination string
	Content     string
	JSON        interface{}
	Status      ValidationResult
}

func (definition *Definition) SetContent(workflow string, templatePath string) {
	meta := strings.Join([]string{
		"# File generated by gflows, do not modify",
		fmt.Sprintf("# Source: %s", templatePath),
	}, "\n")
	definition.Content = meta + "\n" + workflow

	json, err := yaml.YamlToJson(definition.Content)
	if err != nil {
		definition.Status = ValidationResult{
			Valid:  false,
			Errors: []string{err.Error()},
		}
	} else {
		definition.JSON = json
	}
}
